In [249]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [250]:
population = pd.read_csv(r"C:\Users\sathv\OneDrive\Desktop\RDM\adult.data.csv")

In [251]:
sample_1 = population

In [252]:
X= sample_1[["age","workclass","education-num","marital-status","occupation","relationship","race","sex","hoursperweek","native-country"]]
y = sample_1["class"]

In [253]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state = 42)

In [254]:
X_train

age          workclass  education-num       marital-status  \
5514    33          Local-gov             13        Never-married   
19777   36            Private             11   Married-civ-spouse   
10781   58   Self-emp-not-inc              5            Separated   
32240   21            Private             11   Married-civ-spouse   
9876    27            Private             10             Divorced   
...    ...                ...            ...                  ...   
29802   47            Private             13   Married-civ-spouse   
5390    31            Private              8             Divorced   
860     18            Private              7        Never-married   
15795   50   Self-emp-not-inc              9   Married-civ-spouse   
23654   34       Self-emp-inc             13             Divorced   

             occupation    relationship    race      sex  hoursperweek  \
5514     Prof-specialty   Not-in-family   White   Female            50   
19777   Exec-managerial         Husband   White     Male            50   
10781      Craft-repair   Not-in-family   White     Male            40   
32240   Farming-fishing         Husband   White     Male            46   
9876      Other-service   Not-in-family   White     Male            40   
...                 ...             ...     ...      ...           ...   
29802      Craft-repair         Husband   White     Male            40   
5390      Other-service       Unmarried   White   Female            21   
860        Adm-clerical       Own-child   White   Female            20   
15795   Farming-fishing         Husband   White     Male            84   
23654   Farming-fishing   Not-in-family   White     Male            60   

       native-country  
5514    United-States  
19777   United-States  
10781   United-States  
32240   United-States  
9876    United-States  
...               ...  
29802   United-States  
5390    United-States  
860     United-States  
15795   United-States  
23654   United-States  

[26048 rows x 10 columns]

In [255]:
def detect_outlier(data,col):
    # find q1 and q3 values
    q1, q3 = np.percentile(sorted(data[col]), [25, 75])
 
    # compute IRQ
    iqr = q3 - q1
 
    # find lower and upper bounds
    lower_bound = q1 - (1.5 * iqr)
    upper_bound = q3 + (1.5 * iqr)
    print(q1, q3, iqr, lower_bound, upper_bound)
 
    outliers = data[(data[col] < lower_bound) | (data[col] > upper_bound)]
#     outliers = [x for x in data[col] if x < lower_bound or x > upper_bound]
 
    return lower_bound,upper_bound

In [256]:
lower_bound,upper_bound = detect_outlier(X_train,"age")

28.0 48.0 20.0 -2.0 78.0


In [257]:
lower_bound

-2.0

In [258]:
upper_bound

78.0

In [259]:
mode = X_train["age"].mode()

In [260]:
mode

0    28
Name: age, dtype: int64

In [261]:
X_train["age"] = np.where(X_train["age"] < lower_bound, mode, X_train['age'])

In [262]:
X_train["age"] = np.where(X_train["age"] > upper_bound, mode, X_train['age'])

In [263]:
X_train

age          workclass  education-num       marital-status  \
5514    33          Local-gov             13        Never-married   
19777   36            Private             11   Married-civ-spouse   
10781   58   Self-emp-not-inc              5            Separated   
32240   21            Private             11   Married-civ-spouse   
9876    27            Private             10             Divorced   
...    ...                ...            ...                  ...   
29802   47            Private             13   Married-civ-spouse   
5390    31            Private              8             Divorced   
860     18            Private              7        Never-married   
15795   50   Self-emp-not-inc              9   Married-civ-spouse   
23654   34       Self-emp-inc             13             Divorced   

             occupation    relationship    race      sex  hoursperweek  \
5514     Prof-specialty   Not-in-family   White   Female            50   
19777   Exec-managerial         Husband   White     Male            50   
10781      Craft-repair   Not-in-family   White     Male            40   
32240   Farming-fishing         Husband   White     Male            46   
9876      Other-service   Not-in-family   White     Male            40   
...                 ...             ...     ...      ...           ...   
29802      Craft-repair         Husband   White     Male            40   
5390      Other-service       Unmarried   White   Female            21   
860        Adm-clerical       Own-child   White   Female            20   
15795   Farming-fishing         Husband   White     Male            84   
23654   Farming-fishing   Not-in-family   White     Male            60   

       native-country  
5514    United-States  
19777   United-States  
10781   United-States  
32240   United-States  
9876    United-States  
...               ...  
29802   United-States  
5390    United-States  
860     United-States  
15795   United-States  
23654   United-States  

[26048 rows x 10 columns]

In [264]:
y_train

5514       >50K
19777      >50K
10781     <=50K
32240     <=50K
9876      <=50K
          ...  
29802     <=50K
5390      <=50K
860       <=50K
15795     <=50K
23654     <=50K
Name: class, Length: 26048, dtype: object

In [265]:
lower_bound,upper_bound = detect_outlier(X_train,"hoursperweek")

40.0 45.0 5.0 32.5 52.5


In [266]:
lower_bound

32.5

In [267]:
upper_bound

52.5

In [268]:
mode = X_train["hoursperweek"].mode()

In [269]:
mode

0    40
Name: hoursperweek, dtype: int64

In [270]:
X_train["hoursperweek"] = np.where(X_train["hoursperweek"] < lower_bound , mode, X_train['hoursperweek'])

In [271]:
X_train["hoursperweek"] = np.where(X_train["hoursperweek"] > upper_bound, mode, X_train['hoursperweek'])

In [272]:
# lower_bound,upper_bound = detect_outlier(X_test,"age")

In [273]:
# mode = X_test["age"].mode()

In [274]:
# X_test["age"] = np.where(X_test["age"] < lower_bound, mode, X_test['age'])

In [275]:
# X_test["age"] = np.where(X_test["age"] > upper_bound, mode, X_test['age'])

In [276]:
# lower_bound,upper_bound = detect_outlier(X_test,"hoursperweek")

In [277]:
# mode = X_test["hoursperweek"].mode()

In [278]:
# X_test["hoursperweek"] = np.where(X_test["hoursperweek"] < lower_bound , mode, X_test['hoursperweek'])

In [279]:
# X_test["hoursperweek"] = np.where(X_test["hoursperweek"] > upper_bound, mode, X_test['hoursperweek'])

In [280]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

In [281]:
def label_encoding(data,cat_cols):
    if cat_cols is None:
        data= label_encoder.fit_transform(data)
        return data
        
    else:
        for i in range(len(cat_cols)):
            data[cat_cols[i]]= label_encoder.fit_transform(data[cat_cols[i]])
        

In [282]:
cols = X_train.select_dtypes([np.object]).columns

C:\Users\sathv\AppData\Local\Temp\ipykernel_11684\2170981920.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  cols = X_train.select_dtypes([np.object]).columns


In [283]:
cols

Index(['workclass', 'marital-status', 'occupation', 'relationship', 'race',
       'sex', 'native-country'],
      dtype='object')

In [284]:
label_encoding(X_train,cols)

In [285]:
X_train

age  workclass  education-num  marital-status  occupation  \
5514    33          2             13               4          10   
19777   36          4             11               2           4   
10781   58          6              5               5           3   
32240   21          4             11               2           5   
9876    27          4             10               0           8   
...    ...        ...            ...             ...         ...   
29802   47          4             13               2           3   
5390    31          4              8               0           8   
860     18          4              7               4           1   
15795   50          6              9               2           5   
23654   34          5             13               0           5   

       relationship  race  sex  hoursperweek  native-country  
5514              1     4    0            50              39  
19777             0     4    1            50              39  
10781             1     4    1            40              39  
32240             0     4    1            46              39  
9876              1     4    1            40              39  
...             ...   ...  ...           ...             ...  
29802             0     4    1            40              39  
5390              4     4    0            40              39  
860               3     4    0            40              39  
15795             0     4    1            40              39  
23654             1     4    1            40              39  

[26048 rows x 10 columns]

In [286]:
# col = None
y_train = label_encoding(y_train, None)

In [287]:
y_train

array([1, 1, 0, ..., 0, 0, 0])

In [288]:
label_encoding(X_test, cols)

In [289]:
y_test= label_encoding(y_test, None)

In [290]:
y_test

array([0, 0, 1, ..., 1, 0, 0])

In [291]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
logisticRegr = LogisticRegression()

In [292]:
def logistic_regression_train(logisticRegr,x,y):
    logisticRegr.fit(x,y)
def logistic_regression_test(logisticRegr,x):
    y_pred = logisticRegr.predict_proba(x)
    return y_pred
def logistic_regression_pred_test(logisticRegr,x):
    y_pred_test = logisticRegr.predict(x)
    return y_pred_test

def average_diff(y_pred, X_test):
    column_i = y_pred.T[0]
    X_test_copy = X_test.copy()
    X_test_copy['preds'] = column_i
    Female = X_test_copy["preds"][X_test_copy["sex"] == 0]
    female_average = sum(Female)/len(Female)
    male = X_test_copy["preds"][X_test_copy["sex"] == 1]
    male_average = sum(male)/len(male)
    diff = (female_average - male_average)
    return diff 

def accuracy(y_test, y_pred_final):
#     y_pred_final = np.argmax(y_pred, axis=1)
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred_final).ravel()
    true_positive  = tn
    false_positive = fn
    true_negative  = tp
    false_negative = fp
    accuracy = (true_positive + true_negative) / (true_negative + true_positive + false_positive + false_negative )
    return(accuracy)
    
    

In [293]:
model = logistic_regression_train(logisticRegr, X_train, y_train)

C:\Users\sathv\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [294]:
y_pred = logistic_regression_test(logisticRegr, X_test)

In [295]:
y_pred

array([[0.7861054 , 0.2138946 ],
       [0.95402384, 0.04597616],
       [0.67513587, 0.32486413],
       ...,
       [0.34828928, 0.65171072],
       [0.87385509, 0.12614491],
       [0.77155134, 0.22844866]])

In [296]:
dirty_diff = average_diff(y_pred, X_test)

In [297]:
dirty_diff

0.1898730789472589

In [298]:
dirty_test_score = logisticRegr.score(X_test, y_test)

In [299]:
dirty_test_score

0.7584830339321357

In [300]:
X_clean_train, X_clean_test, y_clean_train, y_clean_test = train_test_split(X, y, test_size=0.20, random_state = 42)

In [301]:
lower_bound,upper_bound = detect_outlier(X_clean_train,"age")
mode = X_clean_train["age"].mode()
X_clean_train["age"] = np.where(X_clean_train["age"] < lower_bound, mode, X_clean_train['age'])
X_clean_train["age"] = np.where(X_clean_train["age"] > upper_bound, mode, X_clean_train['age'])


28.0 48.0 20.0 -2.0 78.0


In [302]:
lower_bound,upper_bound = detect_outlier(X_clean_train,"hoursperweek")
mode = X_clean_train["hoursperweek"].mode()
X_clean_train["hoursperweek"] = np.where(X_clean_train["hoursperweek"] < lower_bound , mode, X_clean_train['hoursperweek'])
X_clean_train["hoursperweek"] = np.where(X_clean_train["hoursperweek"] > upper_bound, mode, X_clean_train['hoursperweek'])


40.0 45.0 5.0 32.5 52.5


In [303]:
lower_bound,upper_bound = detect_outlier(X_clean_test,"age")
mode = X_clean_test["age"].mode()
X_clean_test["age"] = np.where(X_clean_test["age"] < lower_bound, mode, X_clean_test['age'])
X_clean_test["age"] = np.where(X_clean_test["age"] > upper_bound, mode, X_clean_test['age'])


28.0 48.0 20.0 -2.0 78.0


In [304]:
lower_bound,upper_bound = detect_outlier(X_clean_test,"hoursperweek")
mode = X_clean_test["hoursperweek"].mode()
X_clean_test["hoursperweek"] = np.where(X_clean_test["hoursperweek"] < lower_bound , mode, X_clean_test['hoursperweek'])
X_clean_test["hoursperweek"] = np.where(X_clean_test["hoursperweek"] > upper_bound, mode, X_clean_test['hoursperweek'])

40.0 45.0 5.0 32.5 52.5


In [305]:
label_encoding(X_clean_train,cols)

In [306]:
y_clean_train = label_encoding(y_clean_train, None)

In [307]:
label_encoding(X_clean_test,cols)

In [308]:
y_clean_test= label_encoding(y_clean_test, None)

In [309]:
clean_model = logistic_regression_train(logisticRegr, X_clean_train, y_clean_train)

C:\Users\sathv\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [310]:
y_clean_pred = logistic_regression_test(logisticRegr, X_clean_test)

In [311]:
y_clean_pred

array([[0.7861054 , 0.2138946 ],
       [0.95402384, 0.04597616],
       [0.46177838, 0.53822162],
       ...,
       [0.34828928, 0.65171072],
       [0.87385509, 0.12614491],
       [0.89107645, 0.10892355]])

In [312]:
clean_diff = average_diff(y_clean_pred, X_clean_test)

In [313]:
clean_diff

0.22328723663101202

In [314]:
clean_test_score = logisticRegr.score(X_clean_test, y_clean_test)

In [315]:
clean_test_score

0.7933364041148472

In [316]:
from tabulate import tabulate
data = [["IQR","Impute Outliers by mode","Dirty test data","Label Encoding", "Logistic Regression", dirty_test_score, dirty_diff],
["IQR","Impute Outliers by mode", "Clean test data", "Label Encoding", "Logistic Regression", clean_test_score, clean_diff]]
print (tabulate(data, headers=["Detect Method","Method", "Test Data", "Encoding Technique", "ML Model", "Accuracy", "Fairness"]))

Detect Method    Method                   Test Data        Encoding Technique    ML Model               Accuracy    Fairness
---------------  -----------------------  ---------------  --------------------  -------------------  ----------  ----------
IQR              Impute Outliers by mode  Dirty test data  Label Encoding        Logistic Regression    0.758483    0.189873
IQR              Impute Outliers by mode  Clean test data  Label Encoding        Logistic Regression    0.793336    0.223287
