In [178]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import LocalOutlierFactor

In [179]:
population = pd.read_csv(r"C:\Users\sathv\OneDrive\Desktop\RDM\adult.data.csv")

In [180]:
sample_1 = population

In [181]:
X= sample_1[["age","workclass","education-num","marital-status","occupation","relationship","race","sex","hoursperweek","native-country"]]
y = sample_1["class"]

In [182]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state = 42)

In [183]:
X_train

age          workclass  education-num       marital-status  \
5514    33          Local-gov             13        Never-married   
19777   36            Private             11   Married-civ-spouse   
10781   58   Self-emp-not-inc              5            Separated   
32240   21            Private             11   Married-civ-spouse   
9876    27            Private             10             Divorced   
...    ...                ...            ...                  ...   
29802   47            Private             13   Married-civ-spouse   
5390    31            Private              8             Divorced   
860     18            Private              7        Never-married   
15795   50   Self-emp-not-inc              9   Married-civ-spouse   
23654   34       Self-emp-inc             13             Divorced   

             occupation    relationship    race      sex  hoursperweek  \
5514     Prof-specialty   Not-in-family   White   Female            50   
19777   Exec-managerial         Husband   White     Male            50   
10781      Craft-repair   Not-in-family   White     Male            40   
32240   Farming-fishing         Husband   White     Male            46   
9876      Other-service   Not-in-family   White     Male            40   
...                 ...             ...     ...      ...           ...   
29802      Craft-repair         Husband   White     Male            40   
5390      Other-service       Unmarried   White   Female            21   
860        Adm-clerical       Own-child   White   Female            20   
15795   Farming-fishing         Husband   White     Male            84   
23654   Farming-fishing   Not-in-family   White     Male            60   

       native-country  
5514    United-States  
19777   United-States  
10781   United-States  
32240   United-States  
9876    United-States  
...               ...  
29802   United-States  
5390    United-States  
860     United-States  
15795   United-States  
23654   United-States  

[26048 rows x 10 columns]

In [184]:
y_train

5514       >50K
19777      >50K
10781     <=50K
32240     <=50K
9876      <=50K
          ...  
29802     <=50K
5390      <=50K
860       <=50K
15795     <=50K
23654     <=50K
Name: class, Length: 26048, dtype: object

In [185]:
def detect_outlier(data,col):
    only_na = []
    new_data = data.copy()
    clf = LocalOutlierFactor(n_neighbors=30)
    normalized_df = (new_data[col]- new_data[col].mean())/new_data[col].std()
    clf.fit_predict(normalized_df.values.reshape(-1,1))
    results = clf.negative_outlier_factor_
    new_data["LOF"] = results.tolist()
    new_data = new_data.query("LOF < -1.5")
    for i in new_data.index:
        only_na.append(i)
    return only_na

In [186]:
def drop_rows(x,only_na):
    new_data = x.copy()
    for i in only_na:
        new_data.drop(i,inplace=True)
#     new_data.drop(only_na,axis=1,inplace=True)
    return new_data

In [187]:
only_na = detect_outlier(X_train,"age")

In [188]:
X_train

age          workclass  education-num       marital-status  \
5514    33          Local-gov             13        Never-married   
19777   36            Private             11   Married-civ-spouse   
10781   58   Self-emp-not-inc              5            Separated   
32240   21            Private             11   Married-civ-spouse   
9876    27            Private             10             Divorced   
...    ...                ...            ...                  ...   
29802   47            Private             13   Married-civ-spouse   
5390    31            Private              8             Divorced   
860     18            Private              7        Never-married   
15795   50   Self-emp-not-inc              9   Married-civ-spouse   
23654   34       Self-emp-inc             13             Divorced   

             occupation    relationship    race      sex  hoursperweek  \
5514     Prof-specialty   Not-in-family   White   Female            50   
19777   Exec-managerial         Husband   White     Male            50   
10781      Craft-repair   Not-in-family   White     Male            40   
32240   Farming-fishing         Husband   White     Male            46   
9876      Other-service   Not-in-family   White     Male            40   
...                 ...             ...     ...      ...           ...   
29802      Craft-repair         Husband   White     Male            40   
5390      Other-service       Unmarried   White   Female            21   
860        Adm-clerical       Own-child   White   Female            20   
15795   Farming-fishing         Husband   White     Male            84   
23654   Farming-fishing   Not-in-family   White     Male            60   

       native-country  
5514    United-States  
19777   United-States  
10781   United-States  
32240   United-States  
9876    United-States  
...               ...  
29802   United-States  
5390    United-States  
860     United-States  
15795   United-States  
23654   United-States  

[26048 rows x 10 columns]

In [189]:
X_train = drop_rows(X_train, only_na)

In [190]:
y_train = drop_rows(y_train, only_na)

In [191]:
only_na = detect_outlier(X_train,"hoursperweek")

In [192]:
X_train = drop_rows(X_train, only_na)

In [193]:
y_train = drop_rows(y_train, only_na)

In [194]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

In [195]:
def label_encoding(data,cat_cols):
    if cat_cols is None:
        data= label_encoder.fit_transform(data)
        return data
        
    else:
        for i in range(len(cat_cols)):
            data[cat_cols[i]]= label_encoder.fit_transform(data[cat_cols[i]])
        

In [196]:
cols = X_train.select_dtypes([np.object]).columns

C:\Users\sathv\AppData\Local\Temp\ipykernel_16660\2170981920.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  cols = X_train.select_dtypes([np.object]).columns


In [197]:
cols

Index(['workclass', 'marital-status', 'occupation', 'relationship', 'race',
       'sex', 'native-country'],
      dtype='object')

In [198]:
label_encoding(X_train,cols)

In [199]:
X_train

age  workclass  education-num  marital-status  occupation  \
5514    33          2             13               4          10   
19777   36          4             11               2           4   
10781   58          6              5               5           3   
32240   21          4             11               2           5   
9876    27          4             10               0           8   
...    ...        ...            ...             ...         ...   
21575   39          4              9               2           7   
29802   47          4             13               2           3   
860     18          4              7               4           1   
15795   50          6              9               2           5   
23654   34          5             13               0           5   

       relationship  race  sex  hoursperweek  native-country  
5514              1     4    0            50              39  
19777             0     4    1            50              39  
10781             1     4    1            40              39  
32240             0     4    1            46              39  
9876              1     4    1            40              39  
...             ...   ...  ...           ...             ...  
21575             0     4    1            43              39  
29802             0     4    1            40              39  
860               3     4    0            20              39  
15795             0     4    1            84              39  
23654             1     4    1            60              39  

[25631 rows x 10 columns]

In [200]:
# col = None
y_train = label_encoding(y_train, None)

In [201]:
y_train

array([1, 1, 0, ..., 0, 0, 0])

In [202]:
label_encoding(X_test, cols)

In [203]:
y_test= label_encoding(y_test, None)

In [204]:
y_test

array([0, 0, 1, ..., 1, 0, 0])

In [205]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
logisticRegr = LogisticRegression()

In [206]:
def logistic_regression_train(logisticRegr,x,y):
    logisticRegr.fit(x,y)
def logistic_regression_test(logisticRegr,x):
    y_pred = logisticRegr.predict_proba(x)
    return y_pred
def logistic_regression_pred_test(logisticRegr,x):
    y_pred_test = logisticRegr.predict(x)
    return y_pred_test

def average_diff(y_pred, X_test):
    column_i = y_pred.T[0]
    X_test_copy = X_test.copy()
    X_test_copy['preds'] = column_i
    Female = X_test_copy["preds"][X_test_copy["sex"] == 0]
    female_average = sum(Female)/len(Female)
    male = X_test_copy["preds"][X_test_copy["sex"] == 1]
    male_average = sum(male)/len(male)
    diff = (female_average - male_average)
    return diff 

def accuracy(y_test, y_pred_final):
#     y_pred_final = np.argmax(y_pred, axis=1)
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred_final).ravel()
    true_positive  = tn
    false_positive = fn
    true_negative  = tp
    false_negative = fp
    accuracy = (true_positive + true_negative) / (true_negative + true_positive + false_positive + false_negative )
    return(accuracy)
    
    

In [207]:
model = logistic_regression_train(logisticRegr, X_train, y_train)

C:\Users\sathv\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [208]:
y_pred = logistic_regression_test(logisticRegr, X_test)

In [209]:
y_pred

array([[0.91756692, 0.08243308],
       [0.95414407, 0.04585593],
       [0.47451853, 0.52548147],
       ...,
       [0.19659806, 0.80340194],
       [0.90708415, 0.09291585],
       [0.94243735, 0.05756265]])

In [210]:
dirty_diff = average_diff(y_pred, X_test)

In [211]:
dirty_diff

0.24933501210153175

In [212]:
dirty_test_score = logisticRegr.score(X_test, y_test)

In [213]:
dirty_test_score

0.8046982957162598

# Clean test data

In [214]:
X_clean_train, X_clean_test, y_clean_train, y_clean_test = train_test_split(X, y, test_size=0.20, random_state = 42)

In [215]:
only_na = detect_outlier(X_clean_train, "age")

In [216]:
X_clean_train = drop_rows(X_clean_train, only_na)

In [217]:
y_clean_train = drop_rows(y_clean_train, only_na)

In [218]:
only_na = detect_outlier(X_clean_train, "hoursperweek")

In [219]:
X_clean_train = drop_rows(X_clean_train, only_na)

In [220]:
y_clean_train = drop_rows(y_clean_train, only_na)

In [221]:
only_na = detect_outlier(X_clean_test, "age")

In [222]:
X_clean_test = drop_rows(X_clean_test, only_na)

In [223]:
y_clean_test = drop_rows(y_clean_test, only_na)

In [224]:
only_na = detect_outlier(X_clean_test, "hoursperweek")

In [225]:
X_clean_test = drop_rows(X_clean_test, only_na)

In [226]:
y_clean_test = drop_rows(y_clean_test, only_na)

In [227]:
label_encoding(X_clean_train,cols)

In [228]:
y_clean_train = label_encoding(y_clean_train, None)

In [229]:
label_encoding(X_clean_test,cols)

In [230]:
y_clean_test= label_encoding(y_clean_test, None)

In [231]:
clean_model = logistic_regression_train(logisticRegr, X_clean_train, y_clean_train)

C:\Users\sathv\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [232]:
y_clean_pred = logistic_regression_test(logisticRegr, X_clean_test)

In [233]:
y_clean_pred

array([[0.91756692, 0.08243308],
       [0.95414407, 0.04585593],
       [0.47451853, 0.52548147],
       ...,
       [0.19659806, 0.80340194],
       [0.90708415, 0.09291585],
       [0.94243735, 0.05756265]])

In [234]:
clean_diff = average_diff(y_clean_pred, X_clean_test)

In [235]:
clean_diff

0.24746873658655466

In [236]:
clean_test_score = logisticRegr.score(X_clean_test, y_clean_test)

In [237]:
clean_test_score

0.8063792274402949

In [238]:
from tabulate import tabulate
data = [["Local Outlier Factor","Removing Outliers","Dirty test data","Label Encoding", "Logistic Regression", dirty_test_score, dirty_diff],
["Local Outlier Factor","Removing Outliers", "Clean test data", "Label Encoding", "Logistic Regression", clean_test_score, clean_diff]]
print (tabulate(data, headers=["Detection Method","Method", "Test Data", "Encoding Technique", "ML Model", "Accuracy", "Fairness"]))

Detection Method      Method             Test Data        Encoding Technique    ML Model               Accuracy    Fairness
--------------------  -----------------  ---------------  --------------------  -------------------  ----------  ----------
Local Outlier Factor  Removing Outliers  Dirty test data  Label Encoding        Logistic Regression    0.804698    0.249335
Local Outlier Factor  Removing Outliers  Clean test data  Label Encoding        Logistic Regression    0.806379    0.247469
